### ISSUE TITLE
请求编写下列wiki

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [Vanilla-Non-Benefit-Community/VanillaGlobalChannel#1]
install VanillaGlobalChannel
build VanillaGlobalChannel
config VanillaGlobalChannel

**Comment by MikkoAyaka** [comment]
收到啦，明天完善Wiki

**Comment by Mr-Ao-Dragon** [comment]
对了，可以写下怎么打成tomcat的包吗？

**Comment by MikkoAyaka** [comment]
打成tomcat的包???我不会...我跳过基础直接学的Springboot...
