### ISSUE TITLE
接入Q群请求

### ISSUE THREAD

**Issue by Tarikys** [Vanilla-Non-Benefit-Community/VanillaGlobalChannel#10]
能否将聊天频道接入Q群，扩展频道范围

**Comment by MikkoAyaka** [comment]
这个需求在一开始我们就有做过相关的考虑，最后决定不将其加入未来开发计划中，有以下几点理由：
1.市面上已经有许多成熟的群服互通方案，基于 MiraiMC 或者 Coloryr 的插件等。
2.这个新功能在定位上违背了”真正的跨服频道“这一核心理念。
综上，我们不会考虑在未来加入QQ群支持相关的功能，频道范围也仅限于 MC 服务器，不会扩展到其它平台。
(不过我们也鼓励其它开发者对这个项目进行二次开发，自行实现相关功能哦)
